apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-pv
spec:
  capacity:
    storage: {{ .Values.mysqlVolume.persistentVolume.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mysqlVolume.persistentVolume.pathOnHost }}
